### ISSUE TITLE
Wrong path

### ISSUE THREAD

**Issue by JPeer264** [lukechilds/parcel-plugin-ogimage#2]
I have following meta tags:

```html
<!-- INPUT -->
<meta property="og:image" content="./img/og_img.png">
<meta property="og:url" content="https://mywebsite.io/someurl">
```

My `--public-path` in parcel is also just `./` which means the image should come from `/someurl`, instead, `/someurl` will get removed so the output looks like following:

```html
<!-- OUTPUT  -->
<meta property="og:image" content="https://mywebsite.io/og_img.123.png">
<meta property="og:url" content="https://mywebsite.io/someurl">
```
----

```html
<!-- EXPECTED OUTPUT  -->
<meta property="og:image" content="https://mywebsite.io/someurl/og_img.123.png">
<meta property="og:url" content="https://mywebsite.io/someurl">
```

**Comment by lukechilds** [comment]
Thanks for reporting. I'm using `url.resolve` to concat the base url with the image file url. Not too sure why that isn't correctly resolving the relative link.

https://github.com/lukechilds/parcel-plugin-ogimage/blob/3ec0050d675ac473177e3b61c07d4397889e85f5/index.js#L38

I don't really have time to look into this but if you want to work on it I'd happily accept a PR.

**Comment by JPeer264** [comment]
Seems like the bug was not in this lib. The image actually did not got resolved correctly and was not originally without the public url. That caused the error.
